---
output:
  rmarkdown::html_vignette: default
  html_document: default
---
dev---
title: "Turorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Turorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(lrm2)
```

# load dataset
```{r}
X.vec <- mtcars$wt
Y <- mtcars$mpg
```

# fit the model with lrm
estimate the parameters
```{r}
m <- lrm(Y, X.vec)
m
```

F-test of the whole model
```{r}
m <- lrm(Y, X.vec, estimate=FALSE, anova=TRUE, Ftest=TRUE)
m
```

partial-test of selected parameter
```{r}
m <- lrm(Y, X.vec, test.variable=2, estimate=FALSE, partialtest=TRUE)
m
```

GLH of a subset of parameters
```{r}
m <- lrm(Y, X.vec, test.matrix=matrix(c(0,1),nrow=1,ncol=2), estimate=FALSE, GLH=TRUE)
m
```

# Compared with the results in lm function
```{r}
m2 = lm(mpg~wt, data = mtcars)
summary(m2)
```

```{r}
library(car)
contrast.T = matrix(c(0,1),nrow=1, ncol=2)
linearHypothesis(model=lm(mpg~wt, data = mtcars), hypothesis.matrix=contrast.T, rhs=c(0))
```

# Time consumption
```{r}
system.time(summary(lm(mpg~wt, data=mtcars)))
system.time(lrm(Y, X.vec))

```
